gnieh/diffson

src/main/scala/gnieh/diffson/JsonPatch.scala, src/test/scala/gnieh/diffson/TestJsonDiff.scala
The `compacted` parameter does not make much sense and, moreover,
prevents spray-json to work correctly.
Remove it makes no harm and makes it work again.
=> [fix #7] Diff with string

project/Build.scala, src/main/scala/gnieh/diffson/JsonDiff.scala, src/test/scala/gnieh/diffson/TestArrayDiff.scala
Subsequent array operations (add/remove/replace) use wrong element indices.
This simple test case will fail:
```scala
val a = Array(1,2,3).toJson
val b = Array(2,4).toJson
val p = JsonDiff.diff(a,b)
p(a)
```
=> Wrong base index is fixed in array diff routine, ScalaCheck test case is added.

src/main/scala/gnieh/diffson/JsonDiff.scala, src/test/scala/gnieh/diffson/TestJsonDiff.scala
It makes no sense to reverse the order of diff operations computed on
values contained in objects. More than that, it makes array diffs crash
if the order ir reversed. Order in object does not matter, so just don't
reverse useless things, even though it is more efficient.
=> [fix #12] Do not reverse diff on object values

src/main/scala/gnieh/diffson/pointer.scala, src/test/resources/conformance/spec_tests.json, src/test/resources/conformance/tests.json, src/test/scala/gnieh/diffson/TestSerialization.scala
JSON pointers with more than one slash were being serialized incorrectly, e.g. "/a/b/c" -> "/abc", which meant that a serialized JSON patch could not be deserialized and applied to a JSON value.
=> Fix serialization of JSON patches

src/main/scala/gnieh/diffson/sprayJson/package.scala
Spray distinguishes between `RootJsonFormat` (for types that serialize to a JSON object or array) and `JsonFormat` (for types that serialize to any JSON type, including invalid root types like string).  This PR makes `JsonPatch` and `Operation` serializable as a root JSON object.
More info here:
https://github.com/spray/spray-json#jsonformat-vs-rootjsonformat
Without this change, it is not possible to use `JsonPatch` in some desirable scenarios, such as in `entity(as[JsonPatch])` in an Akka HTTP route.
=> Extend RootJsonFormat instead of JsonFormat for objects and arrays.

build.sbt, circe/src/main/scala/gnieh/diffson/CirceInstance.scala, circe/src/test/scala/gnieh/diffson/circe/TestArrayDiff.scala, circe/src/test/scala/gnieh/diffson/circe/TestJsonDiff.scala, circe/src/test/scala/gnieh/diffson/circe/TestJsonPatch.scala, circe/src/test/scala/gnieh/diffson/circe/TestJsonPointer.scala, circe/src/test/scala/gnieh/diffson/circe/TestProtocol.scala, circe/src/test/scala/gnieh/diffson/circe/TestSerialization.scala, circe/src/test/scala/gnieh/diffson/conformance/CirceConformance.scala
Added basic circe support. It's copied from my working codebase but it'd be better to have generic test suite for every supported JSON lib.
=> Circe support (fix #33)

circe/src/main/scala/gnieh/diffson/CirceInstance.scala
since circe 0.7.0 Json arrays are represented by Vectors
=> remove unecessary toVector conversion

circe/src/test/scala/gnieh/diffson/circe/TestSimpleDiff.scala, core/src/main/scala/gnieh/diffson/JsonDiff.scala, core/src/test/scala/gnieh/diffson/TestSimpleDiff.scala, playJson/src/test/scala/gnieh/diffson/playJson/TestSimpleDiff.scala, sprayJson/src/test/scala/gnieh/diffson/sprayJson/TestSimpleDiff.scala
This change follows discussion in #53 and on gitter. In some scenarios it may be interesting not to perform diffs on arrays, but just replacing the value by the new array.
The `simpleDiff` method family allows for such diffs, guaranteed without any array diff operations.
Object are still deeply diffed.
=> Add simple diff capabilities

core/src/main/scala/gnieh/diffson/DynamicProgLcs.scala, core/src/main/scala/gnieh/diffson/HashedLcs.scala, core/src/main/scala/gnieh/diffson/JsonDiffSupport.scala, core/src/main/scala/gnieh/diffson/Patience.scala
Last week I encountered a performance problem when comparing large objects (10 MB). The process took more than 1h (yes, 60m).  After profiling I managed to find a few problems and fixed them. After optimizations the diff computes in ~1s on cold VM.
Important: I am using play-json and used only that implemenation for tests.
Test case:
Both of my jsons contain a large array (>10000). There are no common elements - all objects were changed. JsonDiif decided to first run Patience alg for LCS and then fallback to Dynamic impl. LCS computation took more than 99% of the process.
Changes:
1. Added check in Patience LCS to return immediatelly if there are no common elements.
This completely avoids very long computations that occur without this check.
2. Added HashedLcs
JsValues are constantly …
=> Optimized LCS implementations for big arrays.

core/src/main/scala/gnieh/diffson/JsonPatch.scala
Make the error message cleaner when a Move operation attempts to move a
path below its own parent.
=> Cleaner language in Move error exception

build.sbt, circe/src/test/scala/gnieh/diffson/conformance/CirceConformance.scala
.fieldSet has been deprecated in favor of .keys since 0.9.0, and has
since been removed.
https://github.com/circe/circe/pull/696
=> Switch to latest Circe version.

build.sbt
We don't want to include scalatest and scalacheck in our production code.
=> remove test artifacts from core module

README.markdown, circe/src/main/scala/diffson/circe/package.scala, core/src/main/scala/diffson/jsonpatch/JsonDiff.scala, core/src/main/scala/diffson/jsonpatch/JsonPatch.scala, core/src/main/scala/diffson/jsonpatch/package.scala, playJson/src/main/scala/diffson/playJson/DiffsonProtocol.scala, sprayJson/src/main/scala/gnieh/diffson/sprayJson/DiffsonProtocol.scala, testkit/src/main/scala/diffson/TestJsonDiff.scala
Remembering old values on `replace` and `remove` operations makes it
possible to invert patches generated by the diff algorithm.
This reintroduces the feature from diffson 3, that appeared with #21.
=> Make it possible to remember old values

.travis.yml, README.markdown, build.sbt, circe/shared/src/test/scala/diffson/circe/TestProtocol.scala, core/src/main/scala/diffson/jsonpointer/package.scala, core/src/main/scala/diffson/lcs/Patience.scala, core/src/test/scala/diffson/TestLcs.scala, core/src/test/scala/diffson/TestPatienceBigArray.scala, project/plugins.sbt, testkit/shared/src/main/scala/diffson/TestJsonDiff.scala, testkit/shared/src/main/scala/diffson/TestJsonMergeDiff.scala, testkit/shared/src/main/scala/diffson/TestJsonMergePatch.scala, testkit/shared/src/main/scala/diffson/TestJsonPatch.scala, testkit/shared/src/main/scala/diffson/TestJsonPointer.scala, testkit/shared/src/main/scala/diffson/TestSerialization.scala, testkit/shared/src/main/scala/diffson/TestSimpleDiff.scala
=> Add support for scala 2.13.0

build.sbt, core/src/main/scala/diffson/jsonpatch/package.scala, testkit/shared/src/main/scala/diffson/TestSimpleDiff.scala
A simple diff does not need any LCS instance, even when remembering.
Fixes #275
=> Fix simple diff with remember

build.sbt
This RC is out since March and the best option to have something on Scala 3 as development seems pretty much stalled.
Having this would help fs2-data to jump to full Scala 3 support (and on the fly fix some build complications arising from the missing support now).
=> Use 2.10.0-RC6 of Play! Json to enable Scala 3 build

circe/shared/src/main/scala/diffson/circe/package.scala
Thank you for your recent optimization efforts :+1: 
Looking at my usage I found that most of the cost at runtime comes from the integration layer with Circe, more specifically the `apply` and `unapply` function for `JsObject` tend to allocate a lot.
This PR proposes to optimize the `JsObject.apply` by making Circe reuse the input fields `Map` instead of building a new one internally.
As a side effect, Circe will switch its internal representation to `MapAndVectorJsonObject` for its objects which would speed up the `JsObject.unapply` case.
=> Optimization: Reuse Map when when building a Circe JsonObject

.github/workflows/ci.yml, README.markdown, build.sbt, ujson/shared/src/main/scala/diffson/ujson/FieldMissing.scala, ujson/shared/src/main/scala/diffson/ujson/package.scala, ujson/shared/src/test/scala/diffson/ujson/UjsonJsonDiff.scala, ujson/shared/src/test/scala/diffson/ujson/UjsonJsonJsonMergeDiff.scala, ujson/shared/src/test/scala/diffson/ujson/UjsonSimpleDiff.scala, ujson/shared/src/test/scala/diffson/ujson/UjsonTestArrayDiff.scala, ujson/shared/src/test/scala/diffson/ujson/UjsonTestJsonMergePatch.scala, ujson/shared/src/test/scala/diffson/ujson/UjsonTestJsonPatch.scala, ujson/shared/src/test/scala/diffson/ujson/UjsonTestJsonPointer.scala, ujson/shared/src/test/scala/diffson/ujson/UjsonTestProtocol.scala, ujson/shared/src/test/scala/diffson/ujson/UjsonTestSerialization.scala
Add a ujson/upickle implementation
=> add ujson bridge

.github/workflows/ci.yml, build.sbt, project/plugins.sbt
This PR applies the minimal dependency update required to move diffson to Scala Native 0.5.x. It's blocking https://github.com/gnieh/fs2-data/pull/704 and some more libraries down stream
=> Update libs for Scala Native 0.5.x

build.sbt
Let's not release a major version for the scala native version update, but do a minor release.
=> Change base version to release a minor version

.github/workflows/ci.yml, build.sbt, circe/shared/src/test/scala/diffson/circe/CirceTestObjectDiff.scala, core/src/main/scala/diffson/jsonpatch/JsonDiff.scala, project/build.properties, project/plugins.sbt, testkit/shared/src/main/scala/diffson/TestObjectDiff.scala
The recursive call is sadly not in tail position, so it does use stack when comparing sibling fields. This change suspends the recursive call within an `Eval`, which turns it into a stack safe version.
Without the change, the two added tests fail with a `StackOverflow`.
=> Fix stack overflow when diffing wide objects
